(()=>{let FAVORITE_KEY='zhai_favorites',LAST_READ_KEY='zhai_last_read';function getFavorites(){try{return JSON.parse(localStorage.getItem(FAVORITE_KEY))||[]}catch(e){return[]}}function saveFavorites(items){localStorage.setItem(FAVORITE_KEY,JSON.stringify(items))}function getId(url){return url.replace(/\/$/,'').replace(/index\.html$/,'')}function toggleFavorite(){let id=getId(window.location.href);var favorites=getFavorites(),title=document.querySelector('.post-title h1')?.textContent?.trim()||'未知文章',existing=favorites.findIndex(f=>f.id===id);0<=existing?favorites.splice(existing,1):favorites.unshift({id:id,title:title,url:window.location.pathname,time:Date.now()}),saveFavorites(favorites),updateButton(),updatePanel()}function updateButton(){var btn=document.querySelector('.favorite-btn');if(btn){let id=getId(window.location.href);var isFav=getFavorites().some(f=>f.id===id);btn.classList.toggle('active',isFav),btn.querySelector('i').className=isFav?'fa-solid fa-heart':'fa-regular fa-heart',btn.title=isFav?'取消收藏':'收藏文章'}}function updatePanel(){var favorites,list=document.querySelector('.favorite-list');list&&(favorites=getFavorites(),list.innerHTML=0===favorites.length?'<div class="empty-msg">暂无收藏</div>':favorites.map(f=>`
        <a class="list-item" href="${f.url}">
          <span class="item-title">${f.title}</span>
          <button class="item-remove" data-id="${f.id}">×</button>
        </a>
      `).join(''))}function updateLastReadPanel(){var lastRead,list=document.getElementById('last-read-list');list&&(lastRead=function getLastRead(){try{return JSON.parse(localStorage.getItem(LAST_READ_KEY))||null}catch(e){return null}}(),list.innerHTML=lastRead?`
      <a class="list-item" href="${lastRead.url}">
        <span class="item-title">${lastRead.title}</span>
      </a>
    `:'<div class="empty-msg">暂无记录</div>')}function trackLastRead(){var title=document.querySelector('.post-title h1')?.textContent?.trim();title&&!document.querySelector('article[data-sticky="true"]')&&!function saveLastRead(data){localStorage.setItem(LAST_READ_KEY,JSON.stringify(data))}({title:title,url:window.location.pathname,time:Date.now()})}function init(){var favBtn=document.querySelector('.favorite-btn');favBtn&&(favBtn.addEventListener('click',toggleFavorite),updateButton()),updatePanel(),updateLastReadPanel(),document.querySelector('.post-title')&&trackLastRead(),document.addEventListener('click',e=>{e.target.classList.contains('item-remove')?(e.preventDefault(),e.stopPropagation(),function removeFavorite(id){let favorites=getFavorites();saveFavorites(favorites=favorites.filter(f=>f.id!==id)),updatePanel()}(e.target.dataset.id)):(e=e.target.closest('.panel-header'))&&(e=e.closest('.sidebar-panel'))&&e.classList.toggle('open')})}'loading'===document.readyState?document.addEventListener('DOMContentLoaded',init):init()})();